bod/urls.py
from django.conf.urls import url
from bod.views import *

urlpatterns = [
    url(r'^list/$', EmpresasListView.as_view(), name='list-empresa'),
    url(r'^create/$', EmpresasCreateView.as_view(), name='create-empresa'),
    url(r'^detail/(?P<pk>[-\ \w]+)/$', EmpresasDetailView.as_view(), name='detail-empresa'),
    url(r'^update/(?P<pk>[-\ \w]+)/$', EmpresasUpdateView.as_view(), name='update-empresa'),
    url(r'^delete/(?P<pk>[-\ \w]+)/$', EmpresasDeleteView.as_view(), name='delete-empresa'),
]

bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/', include('bod.urls', namespace='bodega')),
    url(r'^producto/', include('producto.urls', namespace='producto')),
    url(r'^pedido/', include('pedido.urls', namespace='pedido')),
    url(r'^', include('login.urls', namespace='login')),

]

login/urls.py
from django.conf.urls import url
from login.views import *
from bod.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
	url(r'^login/$', LoginView.as_view(), name='panel-login'),
	url(r'^logout/$', LogoutView.as_view(), name='panel-logout'),
	url(r'^change/password/$', ChangePassword.as_view(), name='change_password'),
]

producto/urls.py
from django.conf.urls import url
from producto.views import *

urlpatterns = [
    url(r'^list/', ProductosListView.as_view(), name='list-producto'),
    url(r'^create/$', ProductosCreateView.as_view(), name='create-producto'),
    url(r'^detail/(?P<pk>[-\ \w]+)/$', ProductosDetailView.as_view(), name='detail-producto'),
    url(r'^update/(?P<pk>[-\ \w]+)/$', ProductosUpdateView.as_view(), name='update-producto'),
    url(r'^delete/(?P<pk>[-\ \w]+)/$', ProductosDeleteView.as_view(), name='delete-producto'),
]

producto/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

producto/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from bod import forms, models
from login.views import LoginRequiredMixin
# Create your views here.
class ProductosListView(LoginRequiredMixin, ListView):
	model = models.ProductoModel
	template_name = 'producto/productomodel_list.html'

class ProductosDetailView(LoginRequiredMixin, DetailView):
	model = models.ProductoModel
	template_name = 'producto/productomodel_detail.html'

class ProductosCreateView(LoginRequiredMixin, CreateView):
	model = models.ProductoModel
	second_model = models.CalculoModel
	form_class = forms.ProductoForm
	success_url = reverse_lazy('producto:list-producto')
	template_name = 'producto/productomodel_form.html'

	def get_context_data(self, **kwargs):
	    context = super(ProductosCreateView, self).get_context_data(**kwargs)
	    context["datalist"] = models.CategoriaModel.objects.all()
	    return context

	def form_valid(self, form):
                _object = form.save()
                calculo = self.second_model(producto=_object)
                calculo.save()
                return super(ProductosCreateView, self).form_valid(form)

class ProductosUpdateView(LoginRequiredMixin, UpdateView):
	model = models.ProductoModel
	form_class = forms.ProductoForm
	success_url = reverse_lazy('producto:list-producto')
	template_name = 'producto/productomodel_form.html'

class ProductosDeleteView(LoginRequiredMixin, DeleteView):
	model = models.ProductoModel
	success_url = reverse_lazy('producto:list-producto')
	template_name = 'producto/productomodel_confirm_delete.html'

templates/producto/productomodel_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block context %}
<section>
	<h2>Esta Seguro que dease eliminar la empresa {{ object.nombre }}</h2>
	<form method="POST">{% csrf_token %}
		<div>
			<ul>
				<li><h4>Rif: {{ object.tipo_rif }}-{{ object.rif }}</h4></li>
				<li><h4>Nombre: {{ object.nombre }}</h4></li>
				<li><h4>Direccion: {{ object.direccion }}</h4></li>
			</ul>
		</div>
		<div>
			<button type="submit" class="btn blue">Aceptar</button>
			<a href="{% url 'producto:list-producto' %}" class="btn red">Volver</a>
		</div>
	</form>
</section>
{% endblock %}

templates/producto/productomodel_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block context %}

<section>
	<table>
		<thead>
			<tr>
				<th>Codigo</th>
				<th>Nombre Del Producto</th>
				<th>Categoria</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>{{ object.codigo }}</td>
				<td>{{ object.producto }}</td>
				<td>{{ object.categoria }}</td>
			</tr>

		</tbody>	
	</table>
	<div>
		<a href="{% url 'producto:list-producto' %}" class="btn red">Volver</a>
	</div>
</section>


{% endblock %}

templates/producto/productomodel_form.html
{% extends "base.html" %}
{% load staticfiles %}

{% block js %}
<script>
    window.addEventListener("load", function (e) {
        document.getElementsByClassName("id_codigo").onkeypress = soloNumeros;
    });
    function soloNumeros(e){
        var key = e.which | e.keyCode;
        return (key >= 48 && key <= 57);
    }
</script>
{% endblock %}
{% block context %}
<section>
    <br>
    <form method="POST">
        <div class="row container">
            {% csrf_token %}
            {% for i in form %}
            <div class='col
            {% if i.label == "Codigo" %}
            s4 center
            {% elif i.label == "Producto" %}
            s8
            {% else %}
            s12
            {% endif %}'>
            {{ i.label }}
            {{ i }}
            {{ i.error }}
        </div>
        {% endfor %}
        {% comment %}
        <div class="col s12">
            <input type="text" list="categorias">
            <datalist id="categorias">
                {% for i in datalist %}
                <option value="{{ i.departamento }}">{{ i.departamento }}</option>
                {% endfor %}
            </datalist>
        </div>
        {% endcomment %}
        <div class="col s12">
            <br>
            <button type="submit" class="btn blue right">Aceptar</button>
            <a href="{% url 'login:index' %}" class="btn red">Volver</a>
        </div>
    </div>
</form>
</section>
{% endblock %}

templates/producto/productomodel_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block context %}

<section>
	<table>
		<thead>
			<tr>
				<th>Codigo</th>
				<th>Nombre Del Producto</th>
				<th>Categoria</th>
				<th>Opciones</th>
			</tr>
		</thead>
		<tbody>
			{% for object in object_list %}
			<tr>
				<td>{{ object.codigo }}</td>
				<td><a href="{% url 'producto:detail-producto' object.pk %}">{{ object.producto }}</a></td>
				<td>{{ object.categoria }}</td>
				<td><a href="{% url 'producto:detail-producto' object.pk %}">Ver</a> | <a href="{% url 'producto:update-producto' object.pk %}">Actualizar</a> | <a href="{% url 'producto:delete-producto' object.pk %}">Eliminar</a></td>
			</tr>
			{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<th>Codigo</th>
				<th>Nombre Del Producto</th>
				<th>Categoria</th>
				<th>Opciones</th>
			</tr>
		</tfoot>	
	</table>
</section>


{% endblock %}