bod/urls.py
from django.conf.urls import url
from bod.views import *

urlpatterns = [
    url(r'^list/$', EmpresasListView.as_view(), name='list-empresa'),
    url(r'^create/$', EmpresasCreateView.as_view(), name='create-empresa'),
    url(r'^detail/(?P<pk>[-\ \w]+)/$', EmpresasDetailView.as_view(), name='detail-empresa'),
    url(r'^update/(?P<pk>[-\ \w]+)/$', EmpresasUpdateView.as_view(), name='update-empresa'),
    url(r'^delete/(?P<pk>[-\ \w]+)/$', EmpresasDeleteView.as_view(), name='delete-empresa'),
]

bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/', include('bod.urls', namespace='bodega')),
    url(r'^producto/', include('producto.urls', namespace='producto')),
    url(r'^pedido/', include('pedido.urls', namespace='pedido')),
    url(r'^', include('login.urls', namespace='login')),

]

login/urls.py
from django.conf.urls import url
from login.views import *
from bod.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
	url(r'^login/$', LoginView.as_view(), name='panel-login'),
	url(r'^logout/$', LogoutView.as_view(), name='panel-logout'),
	url(r'^change/password/$', ChangePassword.as_view(), name='change_password'),
]

pedido/urls.py
from django.conf.urls import url
from pedido.views import *

urlpatterns = [
    url(r'^create/$', PedidoCreateView.as_view(), name='create-pedido'),
    url(r'^buscar/empresa/$', BuscadorEmpresaView.as_view(), name='buscar-empresa'),
    url(r'^buscar/producto/$', BuscadorProductoView.as_view(), name='buscar-producto'),
    
]

bod/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class EmpresaModel(models.Model):
	tipo = (
			('J','J'),
			('V','V'),
			('E','E'),
			('P','P'),
			('G','G'),
		)
	tipo_rif = models.CharField(max_length=10, null=False, blank=False, choices=tipo)
	rif = models.CharField(max_length=10, null=False, blank=False, unique=True)
	nombre = models.CharField(max_length=100, null=False, blank=False)
	direccion = models.TextField()

	def __str__(self):
		return str(self.nombre)
    
class CategoriaModel(models.Model):
	departamento = models.CharField(max_length=10, null=False, blank=False)

	def __str__(self):
		return str(self.departamento)

class FacturaModel(models.Model):
	codigo = models.CharField(max_length=10, null=False, blank=False, unique=True)
	fecha = models.DateField()
	empresa = models.ForeignKey(
        EmpresaModel,
        on_delete=models.CASCADE,
    )
	def __str__(self):
		return str(self.codigo)

class ProductoModel(models.Model):
	codigo = models.CharField(max_length=50, null=False, blank=False)
	producto = models.CharField(max_length=100, null=False, blank=False)
	categoria = models.ForeignKey(
		CategoriaModel, null=False, blank=False,
		on_delete=models.CASCADE,
		)
	
	def __str__(self):
		return str(self.producto)

class PrecioModel(models.Model):
	fecha = models.DateField(auto_now_add=True,)
	precio_compra = models.DecimalField(max_digits=10, decimal_places=2)
	precio_venta = models.DecimalField(max_digits=10, decimal_places=2)
	producto = models.ForeignKey(
		ProductoModel,
		on_delete=models.CASCADE)

	def __str__(self):
		return str(self.precio)

class DescripcionModel(models.Model):
	cantidad = models.IntegerField(default=0, null=False, blank=False)
	exento = models.BooleanField(default=False)
	producto = models.ForeignKey(
		ProductoModel, 
		on_delete=models.CASCADE)
	codfac = models.ForeignKey(
		FacturaModel,
		on_delete=models.CASCADE,
		)

	def __str__(self):
		return str(self.nombre) 

class VentaModel(models.Model):
	cantidad = models.DecimalField(max_digits=10, decimal_places=2)
	producto = models.ForeignKey(
		ProductoModel,
		on_delete=models.CASCADE)
	def __str__(self):
		return str(self.cantidad)
    

class CalculoModel(models.Model):
        producto = models.ForeignKey(
		ProductoModel,
		on_delete=models.CASCADE)
        n_compra = models.IntegerField(default=0)
        n_venta = models.IntegerField(default=0)

        def __str__(self):
                return str(self.producto)
        

pedido/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

bod/forms.py
from django import forms
from bod.models import *

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class EmpresaForm(forms.ModelForm):
    class Meta:
        model = EmpresaModel
        fields = ('tipo_rif',
                  'rif',
				  'nombre',
				  'direccion',)
        widgets = {
            'direccion': forms.Textarea(
                attrs={
                'autocomplete':'off',
                'class': 'materialize-textarea'
                }),
        }

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = CategoriaModel
        fields = ('departamento',)

class FacturaForm(forms.ModelForm):
    empresa = forms.CharField(max_length=100,)
    class Meta:
        model = FacturaModel
        fields = ('codigo',
                  'fecha',
				  'empresa',)
        widgets = {
            'fecha': DateInput(format = '%Y-%m-%d'),
        }

class ProductoForm(forms.ModelForm):
    class Meta:
        model = ProductoModel
        fields = ('codigo',
				  'producto',
				  'categoria',)

class PrecioForm(forms.ModelForm):
    class Meta:
        model = PrecioModel
        fields = ('precio_compra',
				  'precio_venta',
				  'producto',)

class DescripcionForm(forms.ModelForm):
    class Meta:
        model = DescripcionModel
        fields = ('cantidad',
				  'exento',
				  'producto',
				  'codfac',)

class VentaForm(forms.ModelForm):
    class Meta:
        model = VentaModel
        fields = ('cantidad',
				  'producto',)

pedido/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.shortcuts import render,  get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.core.urlresolvers import reverse_lazy
from bod import forms, models
from login.views import LoginRequiredMixin
# Create your views here.

class PedidoCreateView(CreateView):
	model = models.FacturaModel
	second_model = models.EmpresaModel
	form_class = forms.FacturaForm
	second_form_class = forms.EmpresaModel
	template_name = 'pedido/pedido_form.html'


	def post(self, *args, **kwargs):
		message = ""
		form = self.form_class(self.request.POST)
		empresa = self.second_model.objects.get(pk=self.request.POST.get("empresa"))
		cod = self.model.objects.filter(codigo=str(self.request.POST.get("codigo"))).first()
		if not cod:
			sav = self.model.objects.create(codigo=self.request.POST.get("codigo"), fecha=self.request.POST.get("fecha"), empresa=empresa)
			message = "Creado Exitosamente"
		else:
			message = "Este Codigo Ya Existe"
			return render(self.request, self.template_name, {'form["codigo"]':2323})
		return HttpResponse(message)


class BuscadorEmpresaView(TemplateView):
	model = models.EmpresaModel

	def get(self, *args, **kwargs):
		palabra = self.request.GET.get("name")
		empresa = self.model.objects.filter(nombre__contains = str(palabra))
		data = {}
		acum = 0
		for i in empresa:
			data[acum]={"pk": i.pk, "nombre": i.nombre, "rif": i.rif}
			acum+=1
		return JsonResponse(data)

class BuscadorProductoView(TemplateView):
	model = models.ProductoModel

	def get(self, *args, **kwargs):
		palabra = self.request.GET.get("name")
		empresa = self.model.objects.filter(producto__contains = str(palabra))
		data = {}
		acum = 0
		for i in empresa:
                        #upc: ultimo precio compra - venta
			data[acum]={"pk": i.pk, "codigo": i.codigo, "nombre": i.producto, "upc": "", "upv": "", "exento": ""}
			acum+=1
		return JsonResponse(data)

templates/pedido/pedido_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% block js %}
<style>
    .autoc{
        margin-bottom: 0px !important;
    }
    .lbchb{
        padding: 0px 8px !important;
    }
</style>
<script src= "{% static '/js/handlebars.js' %}"></script>
<script src= "{% static '/js/typeahead.bundle.min.js' %}"></script>
<script>
    var dir_empresa = "{% url 'pedido:buscar-empresa' %}";
    var dir_producto = "{% url 'pedido:buscar-producto' %}";
</script>
<script src= "{% static '/js/buscador.js' %}"></script>
{% endblock %}
{% block context %}
<section>
    <br>
    <form method="POST" id="form_pedido">
        <div class="row container">{% csrf_token %}{% for i in form %}
            <div class='col
                 {% if i.label == "Codigo" %}s4 center
                 {% elif i.label == "Fecha" %}s8
                 {% else %}s12{% endif %}'>
                <b>{{ i.label }}</b>
                {% if i.label == "Empresa" %}
                <input type="hidden" name="empresa" id="id_empresa" class="hide">
                <input type="text" name="empresa2" maxlength="100" required id="id_empresa2" class="autoc"><div>
                <div class="col s12" style="margin-bottom: 20px;">
                {% else %}{{ i }}{% endif %}
                {{ i.errors }}
            </div>
            {% if i.label == "Empresa" %}{% endif %}{% endfor %}
            <div class="col s12 no-padding center">
                <div class="col s1 center">Cant</div>
                <div class="col s4">Producto</div>
                <div class="col s1 center">E</div>
                <div class="col s3">Precio Unitario</div>
                <div class="col s3">Precio Total</div>
            </div>
            <div class="col s12 no-padding" id="productos"></div>
            <div id="copiaProd" class="col s12  no-padding hide">
                <div class="col s1 center">
                    <input type="text" name="cant[]" id="id_cant" required class="solon" value="1" disabled>
                </div>
                <div class="col s4">
                    <input type="text" name="producto[]" maxlength="100" required id="id_producto" class="autoc" autocomplete="off">
                </div>
                <div class="col s1 center">
                    <p>
                        <input type="checkbox" name="exento[]" id="id_exento" disabled>
                        <label class="lbchb" for="exc"></label>
                    </p>
                </div>
                <div class="col s3">
                    <input type="text" name="precioc[]" maxlength="100" required id="id_precioc" class="solon" autocomplete="off" disabled>
                    <input type="hidden" class="hide" value="">
                </div>
                <div class="col s3">
                    <input type="text" name="preciov[]" maxlength="100" required id="id_preciov" class="solon" autocomplete="off" disabled>
                </div>
            </div>
            <div class="col s12">
                <br>
                <button type="submit" class="btn blue right">Aceptar</button>
                <a href="{% url 'login:index' %}" class="btn red">Volver</a>
            </div>
        </div>
    </form>
    <div id="modal1" class="modal modal-fixed-footer">
        <div class="modal-content">
            <h4>Modal Header</h4>
            <p>A bunch of text</p>
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
        </div>
    </div>
</section>
{% endblock %}