bod/urls.py
from django.conf.urls import url
from bod.views import *

urlpatterns = [
    url(r'^list/$', EmpresasListView.as_view(), name='list-empresa'),
    url(r'^create/$', EmpresasCreateView.as_view(), name='create-empresa'),
    url(r'^detail/(?P<pk>[-\ \w]+)/$', EmpresasDetailView.as_view(), name='detail-empresa'),
    url(r'^update/(?P<pk>[-\ \w]+)/$', EmpresasUpdateView.as_view(), name='update-empresa'),
    url(r'^delete/(?P<pk>[-\ \w]+)/$', EmpresasDeleteView.as_view(), name='delete-empresa'),
]

bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/', include('bod.urls', namespace='bodega')),
    url(r'^producto/', include('producto.urls', namespace='producto')),
    url(r'^pedido/', include('pedido.urls', namespace='pedido')),
    url(r'^', include('login.urls', namespace='login')),

]

login/urls.py
from django.conf.urls import url
from login.views import *
from bod.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
	url(r'^login/$', LoginView.as_view(), name='panel-login'),
	url(r'^logout/$', LogoutView.as_view(), name='panel-logout'),
	url(r'^change/password/$', ChangePassword.as_view(), name='change_password'),
]

pedido/urls.py
from django.conf.urls import url
from pedido.views import *

urlpatterns = [
    url(r'^create/$', PedidoCreateView.as_view(), name='create-pedido'),
    url(r'^buscar/empresa/$', BuscadorEmpresaView.as_view(), name='buscar-empresa'),
    url(r'^buscar/producto/$', BuscadorProductoView.as_view(), name='buscar-producto'),
    
]

producto/urls.py
from django.conf.urls import url
from producto.views import *

urlpatterns = [
    url(r'^list/', ProductosListView.as_view(), name='list-producto'),
    url(r'^create/$', ProductosCreateView.as_view(), name='create-producto'),
    url(r'^detail/(?P<pk>[-\ \w]+)/$', ProductosDetailView.as_view(), name='detail-producto'),
    url(r'^update/(?P<pk>[-\ \w]+)/$', ProductosUpdateView.as_view(), name='update-producto'),
    url(r'^delete/(?P<pk>[-\ \w]+)/$', ProductosDeleteView.as_view(), name='delete-producto'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<title>{% block title %} {% endblock %}</title>
	<link rel="stylesheet" href="{% static '/css/materialize.css' %}">
	<link rel="stylesheet" href="{% static '/css/style.css' %}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<script src= "{% static '/js/jquery-3.2.1.min.js' %}"></script>
	<script src= "{% static '/js/materialize.js' %}"></script>
	<script>
	window.addEventListener("load", function (arg) {
		$(".button-collapse").sideNav();
		$("select").material_select();
		$("select").css({"display": "block", "z-index": "-99", "opacity": "0", "position": "absolute"});
	});
	</script>
</head>
<body>
	<nav class="white" role="navigation">
		<div class="nav-wrapper container">
			<a id="logo-container" href="#" class="brand-logo blue-text">Glabal</a>
			{% if request.user.is_authenticated %}
			<a href="#" class="button-collapse right blue-text" data-activates="slide-out"><i class="material-icons">menu</i></a>
			{% endif %}
			<ul id="slide-out" class="side-nav">
				<li><div class="user-view" style="height:200px">
					<div class="background" >
						<img src="{% static '/image/image1.jpg' %}" width="340" >
					</div>					
				</div></li>
				<li><a href="#!"><i class="material-icons blue-text ">person</i>{{ request.user|upper }}</a></li>
				<li><div class="divider"></div></li>
				
				<li class="no-padding">
					<ul class="collapsible collapsible-accordion">
						<li class="bold"><a class="collapsible-header waves-effect waves-teal"><i class="material-icons right">arrow_drop_down</i>Registro</a>
							<div class="collapsible-body">
								<ul>
									<li><a href="{% url 'bodega:create-empresa' %}"  ><i class="material-icons blue-text">business</i>Empresa</a></li>
									<li><a href="{% url 'producto:create-producto' %}"  ><i class="material-icons blue-text">shopping_cart</i>Producto</a></li>
									<li><a href="{% url 'pedido:create-pedido' %}"  ><i class="material-icons blue-text">assignment</i>Pedido</a></li>
									<li><a href="#!"  ><i class="material-icons blue-text">assignment_return</i>Ventas</a></li>
								</ul>
							</div>
						</li>
						<li class="bold"><a class="collapsible-header waves-effect waves-teal"><i class="material-icons right">arrow_drop_down</i>Consulta</a>
							<div class="collapsible-body">
								<ul>
									<li><a href="{% url 'bodega:list-empresa' %}"  ><i class="material-icons blue-text">business</i>Empresas</a></li>
									<li><a href="{% url 'producto:list-producto' %}"  ><i class="material-icons blue-text">shopping_cart</i>Producto</a></li>
									<li><a href="#!"  ><i class="material-icons blue-text">assignment</i>Inventario</a></li>
									<li><a href="#!"  ><i class="material-icons blue-text">shopping_cart</i>Compra-Ventas</a></li>
								</ul>
							</div>
						</li>
						<li class="bold"><a class="collapsible-header waves-effect waves-teal "><i class="material-icons right">arrow_drop_down</i>Reporte</a>
							<div class="collapsible-body">
								<ul>
									<li><a href="#!"  ><i class="material-icons blue-text">assignment</i>Inventario</a></li>
									<li><a href="#!"  ><i class="material-icons blue-text">shopping_cart</i>Compra-Ventas</a></li>
								</ul>
							</div>
						</li>
						<li class="bold"><a class="collapsible-header waves-effect waves-teal "><i class="material-icons right">arrow_drop_down</i>Configuración</a>
							<div class="collapsible-body">
								<ul>
									<li><a href="#!"  ><i class="material-icons blue-text">vpn_key</i>Cambiar Contraseña</a></li>
								</ul>
							</div>
						</li>
						<li><div class="divider"></div></li>
						<li class="bold"><a href="{% url 'login:panel-logout' %}" class="collapsible-header waves-effect waves-teal "><i class="material-icons left red-text">lock</i>Cerrar Sesi&oacute;n</a>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
	{% block context %}

	{% endblock %}

	{% block js %}

	{% endblock %}
</body>
</html>