bod/urls.py
from django.conf.urls import url
from bod.views import *

urlpatterns = [
    url(r'^list/$', EmpresasListView.as_view(), name='list-empresa'),
    url(r'^create/$', EmpresasCreateView.as_view(), name='create-empresa'),
    url(r'^detail/(?P<pk>[-\ \w]+)/$', EmpresasDetailView.as_view(), name='detail-empresa'),
    url(r'^update/(?P<pk>[-\ \w]+)/$', EmpresasUpdateView.as_view(), name='update-empresa'),
    url(r'^delete/(?P<pk>[-\ \w]+)/$', EmpresasDeleteView.as_view(), name='delete-empresa'),
]

bodega/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/', include('bod.urls', namespace='bodega')),
    url(r'^producto/', include('producto.urls', namespace='producto')),
    url(r'^pedido/', include('pedido.urls', namespace='pedido')),
    url(r'^', include('login.urls', namespace='login')),

]

login/urls.py
from django.conf.urls import url
from login.views import *
from bod.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
	url(r'^login/$', LoginView.as_view(), name='panel-login'),
	url(r'^logout/$', LogoutView.as_view(), name='panel-logout'),
	url(r'^change/password/$', ChangePassword.as_view(), name='change_password'),
]

bod/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class EmpresaModel(models.Model):
	tipo = (
			('J','J'),
			('V','V'),
			('E','E'),
			('P','P'),
			('G','G'),
		)
	tipo_rif = models.CharField(max_length=10, null=False, blank=False, choices=tipo)
	rif = models.CharField(max_length=10, null=False, blank=False, unique=True)
	nombre = models.CharField(max_length=100, null=False, blank=False)
	direccion = models.TextField()

	def __str__(self):
		return str(self.nombre)
    
class CategoriaModel(models.Model):
	departamento = models.CharField(max_length=10, null=False, blank=False)

	def __str__(self):
		return str(self.departamento)

class FacturaModel(models.Model):
	codigo = models.CharField(max_length=10, null=False, blank=False, unique=True)
	fecha = models.DateField()
	empresa = models.ForeignKey(
        EmpresaModel,
        on_delete=models.CASCADE,
    )
	def __str__(self):
		return str(self.codigo)

class ProductoModel(models.Model):
	codigo = models.CharField(max_length=50, null=False, blank=False)
	producto = models.CharField(max_length=100, null=False, blank=False)
	categoria = models.ForeignKey(
		CategoriaModel, null=False, blank=False,
		on_delete=models.CASCADE,
		)
	
	def __str__(self):
		return str(self.producto)

class PrecioModel(models.Model):
	fecha = models.DateField(auto_now_add=True,)
	precio_compra = models.DecimalField(max_digits=10, decimal_places=2)
	precio_venta = models.DecimalField(max_digits=10, decimal_places=2)
	producto = models.ForeignKey(
		ProductoModel,
		on_delete=models.CASCADE)

	def __str__(self):
		return str(self.precio)

class DescripcionModel(models.Model):
	cantidad = models.IntegerField(default=0, null=False, blank=False)
	exento = models.BooleanField(default=False)
	producto = models.ForeignKey(
		ProductoModel, 
		on_delete=models.CASCADE)
	codfac = models.ForeignKey(
		FacturaModel,
		on_delete=models.CASCADE,
		)

	def __str__(self):
		return str(self.nombre) 

class VentaModel(models.Model):
	cantidad = models.DecimalField(max_digits=10, decimal_places=2)
	producto = models.ForeignKey(
		ProductoModel,
		on_delete=models.CASCADE)
	def __str__(self):
		return str(self.cantidad)
    

class CalculoModel(models.Model):
        producto = models.ForeignKey(
		ProductoModel,
		on_delete=models.CASCADE)
        n_compra = models.IntegerField(default=0)
        n_venta = models.IntegerField(default=0)

        def __str__(self):
                return str(self.producto)
        

bod/forms.py
from django import forms
from bod.models import *

class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class EmpresaForm(forms.ModelForm):
    class Meta:
        model = EmpresaModel
        fields = ('tipo_rif',
                  'rif',
				  'nombre',
				  'direccion',)
        widgets = {
            'direccion': forms.Textarea(
                attrs={
                'autocomplete':'off',
                'class': 'materialize-textarea'
                }),
        }

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = CategoriaModel
        fields = ('departamento',)

class FacturaForm(forms.ModelForm):
    empresa = forms.CharField(max_length=100,)
    class Meta:
        model = FacturaModel
        fields = ('codigo',
                  'fecha',
				  'empresa',)
        widgets = {
            'fecha': DateInput(format = '%Y-%m-%d'),
        }

class ProductoForm(forms.ModelForm):
    class Meta:
        model = ProductoModel
        fields = ('codigo',
				  'producto',
				  'categoria',)

class PrecioForm(forms.ModelForm):
    class Meta:
        model = PrecioModel
        fields = ('precio_compra',
				  'precio_venta',
				  'producto',)

class DescripcionForm(forms.ModelForm):
    class Meta:
        model = DescripcionModel
        fields = ('cantidad',
				  'exento',
				  'producto',
				  'codfac',)

class VentaForm(forms.ModelForm):
    class Meta:
        model = VentaModel
        fields = ('cantidad',
				  'producto',)

bod/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from bod import forms, models
from login.views import LoginRequiredMixin
# Create your views here.
class IndexView(LoginRequiredMixin, TemplateView):
	template_name = 'bod/index.html'

class EmpresasListView(LoginRequiredMixin, ListView):
	model = models.EmpresaModel

class EmpresasDetailView(LoginRequiredMixin, DetailView):
	model = models.EmpresaModel

class EmpresasCreateView(LoginRequiredMixin, CreateView):
	model = models.EmpresaModel
	form_class = forms.EmpresaForm
	success_url = reverse_lazy('bodega:list-empresa')

class EmpresasUpdateView(LoginRequiredMixin, UpdateView):
	model = models.EmpresaModel
	form_class = forms.EmpresaForm
	success_url = reverse_lazy('bodega:list-empresa')

class EmpresasDeleteView(LoginRequiredMixin, DeleteView):
	model = models.EmpresaModel
	success_url = reverse_lazy('bodega:list-empresa')

templates/bod/empresamodel_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block context %}
<section>
	<h2>Esta Seguro que dease eliminar la empresa {{ object.nombre }}</h2>
	<form method="POST">{% csrf_token %}
		<div>
			<ul>
				<li><h4>Rif: {{ object.tipo_rif }}-{{ object.rif }}</h4></li>
				<li><h4>Nombre: {{ object.nombre }}</h4></li>
				<li><h4>Direccion: {{ object.direccion }}</h4></li>
			</ul>
		</div>
		<div>
			<button type="submit" class="btn blue">Aceptar</button>
			<a href="{% url 'bodega:list-empresa' %}" class="btn red">Volver</a>
		</div>
	</form>
</section>
{% endblock %}

templates/bod/empresamodel_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block context %}

<section>
	<table>
		<thead>
			<tr>
				<th>Rif</th>
				<th>Nombre</th>
				<th>Direccion</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>{{ object.tipo_rif }}-{{ object.rif }}</td>
				<td>{{ object.nombre }}</td>
				<td>{{ object.direccion }}</td>
			</tr>

		</tbody>	
	</table>
	<div>
		<a href="{% url 'bodega:list-empresa' %}" class="btn red">Volver</a>
	</div>
</section>


{% endblock %}

templates/bod/empresamodel_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% block js %}
<script>
window.addEventListener("load", function (e) {
    document.getElementById("id_rif").onkeypress = soloNumeros;
});
function soloNumeros(e){
    var key = e.which | e.keyCode;
    return (key >= 48 && key <= 57);
}
</script>
{% endblock %}
{% block context %}
<section>
    <br>
    <form method="POST">
        <div class="row container">
            {% csrf_token %}
            {% for i in form %}
            <div class='col
            {% if i.label == "Tipo rif" %}s4 center
            {% elif i.label == "Rif" %}s8
            {% else %}s12
            {% endif %}'>
            {{ i.label }}
            {{ i }}
            {{ i.error }}
        </div>
        {% endfor %}
        <div class="col s12">
            <br>
            <button type="submit" class="btn blue right">Aceptar</button>
            <a href="{% url 'login:index' %}" class="btn red">Volver</a>
        </div>
    </div>
</form>
</section>
{% endblock %}

templates/bod/empresamodel_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block context %}

<section>
	<table>
		<thead>
			<tr>
				<th>Rif</th>
				<th>Nombre</th>
				<th>Direccion</th>
				<th>Opciones</th>
			</tr>
		</thead>
		<tbody>
			{% for object in object_list %}
			<tr>
				<td>{{ object.tipo_rif }}-{{ object.rif }}</td>
				<td><a href="{% url 'bodega:detail-empresa' object.pk %}">{{ object.nombre }}</a></td>
				<td>{{ object.direccion }}</td>
				<td><a href="{% url 'bodega:detail-empresa' object.pk %}">Ver</a> | <a href="{% url 'bodega:update-empresa' object.pk %}">Actualizar</a> | <a href="{% url 'bodega:delete-empresa' object.pk %}">Eliminar</a></td>
			</tr>
			{% endfor %}
		</tbody>
		<tfoot>
			<tr>
				<th>Rif</th>
				<th>Nombre</th>
				<th>Direccion</th>
			</tr>
		</tfoot>	
	</table>
</section>


{% endblock %}

templates/bod/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block context %}
<script>
window.addEventListener("load", function (arg) {
	$('.carousel.carousel-slider').carousel(
	{
		fullWidth: true,
		duration: 100,
	}
	);

	function autoplay() {
		$('.carousel').carousel('next');
		setTimeout(autoplay, 4500);
	}

	autoplay()
});
</script>

<style>
.carousel-item img{
	height: 500px;
}
.pfa{
	text-shadow: 1px 1px 2px black;
}
</style>
<section class="row">
	<div class="container center" style="margin-top: 4px;">
		<div class="col s12 no-padding">
			<div class="carousel carousel-slider center" data-indicators="true" >
				<a class="carousel-item" href="#one!"><img src="{% static '/image/image1.jpg' %}"></a>
				<a class="carousel-item" href="#one!"><img src="{% static '/image/image2.jpg' %}"></a>
				<a class="carousel-item" href="#one!"><img src="{% static '/image/image3.jpg' %}"></a>
				<a class="carousel-item" href="#one!"><img src="{% static '/image/image4.jpg' %}"></a>
			</div>
		</div>
	</div>
</section>
{% endblock %}